name: benchmark_dotnet_linux

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  ITERATION_COUNT: 1
  BASE_VERSION: 6.0.202
  BASE_VERSION_WINDOWS: https://download.visualstudio.microsoft.com/download/pr/b1461027-6daa-467d-aebe-6326343e5840/01656d95b28f16c53cd947a8072d004b/dotnet-sdk-6.0.202-win-x64.zip
  BASE_VERSION_LINUX: https://download.visualstudio.microsoft.com/download/pr/9d8c7137-2091-4fc6-a419-60ba59c8b9de/db0c5cda94f31d2260d369123de32d59/dotnet-sdk-6.0.202-linux-x64.tar.gz
  DEV_VERSION: dev.2d93510ef                    
  BRANCH_VERSION: walker.854c04d6f                          
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  benchmark_nuget_windows:
    runs-on: windows-2019
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout test solutions
        run: |
          git clone --recursive https://github.com/dotnet/orleans
          git clone --recursive https://github.com/OrchardCMS/OrchardCore.git
          git clone --recursive https://github.com/NuGet/NuGet.Client.git
          git clone --recursive https://github.com/marcin-krystianc/TestSolutions

      - name: Disable strong name verification
        run: |
          reg DELETE "HKLM\Software\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f
          reg DELETE "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f
      
      - name: Setup .NET Core SDK ${{env.BASE_VERSION}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.202
          
      - name: Benchmark
        shell: pwsh
        run: |
          # $solutions = @("NuGet.Client", "OrchardCore", "orleans", "TestSolutions/SanitisedNetCoreApp3.1Centralised", "TestSolutions/SanitisedNetCoreApp3.1")
          $solutions = @("TestSolutions/SanitisedNetCoreApp3.1Centralised")
          $versions = @("${{env.DEV_VERSION}}", "${{env.BRANCH_VERSION}}")
          For ($i=0; $i -lt 2; $i++) {
              ForEach ($solution In $solutions) {
                  ForEach ($version In $versions) {
                    .\scripts\perftests\RunPerformanceTests.ps1 -nugetClientFilePath .\artifacts\$version\NuGet.CommandLine\bin\Release\net472\NuGet.exe  -solutionFilePath $solution -resultsFilePath results.csv -skipForceRestores -skipNoOpRestores -skipColdRestores -iterationCount ${{env.ITERATION_COUNT}} -staticGraphRestore
                  }
              }
          }

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: results_windows_nuget_${{github.run_id}}
          path: results.csv

  benchmark_dotnet_windows:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download .NET Core SDK ${{env.BASE_VERSION}}
        shell: pwsh
        run: |
          curl -sSL ${{env.BASE_VERSION_WINDOWS}} -o dotnet.zip
          Expand-Archive dotnet.zip -DestinationPath dotnet
          # Add(prepend) local dotnet to the system PATH
          echo "$env:GITHUB_WORKSPACE\dotnet" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
         
      - name: Prepare test SDKs
        shell: pwsh
        run: |
          $versions = @("${{env.DEV_VERSION}}", "${{env.BRANCH_VERSION}}")
          ForEach ($version In $versions) {
              Copy-Item -Path .\dotnet\sdk\${{env.BASE_VERSION}} -Destination .\dotnet\sdk\${{env.BASE_VERSION}}-$version -Recurse
              Copy-Item -Path .\artifacts\$version\NuGet.Build.Tasks.Console\bin\Release\netcoreapp5.0\* -Destination .\dotnet\sdk\${{env.BASE_VERSION}}-$version 
              $content = Get-Content -Path .\dotnet\sdk\${{env.BASE_VERSION}}-$version\.version
              $newcontent = $content -replace "${{env.BASE_VERSION}}", "${{env.BASE_VERSION}}-$version"
              Set-Content -Path .\dotnet\sdk\${{env.BASE_VERSION}}-$version\.version -Value $newcontent
              Get-Content -Path .\dotnet\sdk\${{env.BASE_VERSION}}-$version\.version
          }
          Get-ChildItem .
          Get-ChildItem .\dotnet\sdk\

      - name: Checkout test solutions
        shell: pwsh
        run: |
          git clone --recursive https://github.com/dotnet/orleans
          git clone --recursive https://github.com/OrchardCMS/OrchardCore.git
          git clone --recursive https://github.com/NuGet/NuGet.Client.git
          git clone --recursive https://github.com/marcin-krystianc/TestSolutions
          Remove-Item -Path 'orleans\global.json'
          Remove-Item -Path 'NuGet.Client\global.json'

      - name: Disable strong name verification
        shell: pwsh
        run: |
          reg DELETE "HKLM\Software\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f
          reg DELETE "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f
 
      - name: Benchmark
        shell: pwsh
        run: |
          $nugetFoldersPath = [System.IO.Path]::GetFullPath(".nuget")
          $solutions = @("orleans", "NuGet.Client", "OrchardCore", "TestSolutions/SanitisedNetCoreApp3.1Centralised", "TestSolutions/SanitisedNetCoreApp3.1")
          # $solutions = @("TestSolutions/SanitisedNetCoreApp3.1Centralised")
          $versions = @("${{env.BASE_VERSION}}-${{env.DEV_VERSION}}", "${{env.BASE_VERSION}}-${{env.BRANCH_VERSION}}", "${{env.BASE_VERSION}}")
          For ($i=0; $i -lt 2; $i++) {
              ForEach ($solution In $solutions) {
                  ForEach ($version In $versions) {
                    $sdk = '{"sdk": { "version": "' + $version + '" } }'
                    Set-Content -Path global.json -Value $sdk   
                    Get-Content -Path global.json
                    .\scripts\perftests\RunPerformanceTests.ps1 -nugetClientFilePath .\dotnet\dotnet.exe -solutionFilePath $solution -resultsFilePath results.csv -iterationCount ${{env.ITERATION_COUNT}} -staticGraphRestore -nugetFoldersPath $nugetFoldersPath  
                  }
              }
          }
          
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: results_windows_dotnet_${{github.run_id}}
          path: results.csv

  benchmark_dotnet_linux:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download .NET Core SDK ${{env.BASE_VERSION}}
        shell: pwsh
        run: |
          curl -sSL ${{env.BASE_VERSION_LINUX}} -o dotnet.tar.gz
          New-Item -Name "dotnet" -ItemType "directory"
          tar -xf dotnet.tar.gz -C dotnet
          # Add(prepend) local dotnet to the system PATH
          echo "$env:GITHUB_WORKSPACE/dotnet" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Prepare test SDKs
        shell: pwsh
        run: |
          $versions = @("${{env.DEV_VERSION}}", "${{env.BRANCH_VERSION}}")
          ForEach ($version In $versions) {
              Copy-Item -Path .\dotnet\sdk\${{env.BASE_VERSION}} -Destination .\dotnet\sdk\${{env.BASE_VERSION}}-$version -Recurse
              Copy-Item -Path .\artifacts\$version\NuGet.Build.Tasks.Console\bin\Release\netcoreapp5.0\* -Destination .\dotnet\sdk\${{env.BASE_VERSION}}-$version
              $content = Get-Content -Path .\dotnet\sdk\${{env.BASE_VERSION}}-$version\.version
              $newcontent = $content -replace "${{env.BASE_VERSION}}", "${{env.BASE_VERSION}}-$version"
              Set-Content -Path .\dotnet\sdk\${{env.BASE_VERSION}}-$version\.version -Value $newcontent
          }
          Get-ChildItem .
          Get-ChildItem .\dotnet\sdk\

      - name: Checkout test solutions
        shell: pwsh
        run: |
          git clone --recursive https://github.com/dotnet/orleans
          git clone --recursive https://github.com/OrchardCMS/OrchardCore.git
          git clone --recursive https://github.com/NuGet/NuGet.Client.git
          git clone --recursive https://github.com/marcin-krystianc/TestSolutions
          Remove-Item -Path 'orleans\global.json'
          Remove-Item -Path 'NuGet.Client\global.json'
  
      - name: Benchmark
        shell: pwsh
        run: |
          $solutions = @("orleans", "OrchardCore", "TestSolutions/SanitisedNetCoreApp3.1Centralised", "TestSolutions/SanitisedNetCoreApp3.1")
          # $solutions = @("TestSolutions/SanitisedNetCoreApp3.1Centralised")
          $versions = @("${{env.BASE_VERSION}}-${{env.DEV_VERSION}}", "${{env.BASE_VERSION}}-${{env.BRANCH_VERSION}}", "${{env.BASE_VERSION}}")
          For ($i=0; $i -lt 2; $i++) {
              ForEach ($solution In $solutions) {
                  ForEach ($version In $versions) {
                    $sdk = '{"sdk": { "version": "' + $version + '" } }'
                    Set-Content -Path global.json -Value $sdk
                    Get-Content -Path global.json
                    .\scripts\perftests\RunPerformanceTests.ps1 -nugetClientFilePath dotnet/dotnet -solutionFilePath $solution -resultsFilePath results.csv -skipForceRestores -skipNoOpRestores -skipColdRestores -iterationCount ${{env.ITERATION_COUNT}} -staticGraphRestore -nugetFoldersPath $nugetFoldersPath  
                  }
              }
          }

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: results_linux_dotnet_${{github.run_id}}
          path: results.csv
