name: benchmark_dotnet_windows

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  ITERATION_COUNT: 5
  BASE_VERSION: dev.838751441
  BRANCH_VERSION: nommap.5a8b1c47a
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  benchmark_dotnet_windows:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download .NET Core SDK
        run: |
          curl -sSL https://download.visualstudio.microsoft.com/download/pr/c974c8da-7693-41c9-a874-712918a8964e/1d9223b00447537fef5f863cfa88cf80/dotnet-sdk-6.0.100-preview.7.21379.14-win-x64.zip -o dotnet.zip
          Expand-Archive dotnet.zip -DestinationPath dotnet

      - name: Prepare v6.0.100-${{env.BASE_VERSION}}
        run: |
          Copy-Item -Path .\dotnet\sdk\6.0.100-preview.7.21379.14 -Destination .\dotnet\sdk\6.0.100-${{env.BASE_VERSION}} -Recurse
          Copy-Item -Path .\artifacts\${{env.BASE_VERSION}}\NuGet.Build.Tasks\bin\Release\netstandard2.0\* -Destination .\dotnet\sdk\6.0.100-${{env.BASE_VERSION}}
          $content = Get-Content -Path .\dotnet\sdk\6.0.100-${{env.BASE_VERSION}}\.version
          $newcontent = $content -replace '6.0.100-preview.7.21379.14', '6.0.100-${{env.BASE_VERSION}}'
          Set-Content -Path '.\dotnet\sdk\6.0.100-${{env.BASE_VERSION}}\.version' -Value $newcontent

      - name: Prepare v6.0.100-${{env.BRANCH_VERSION}}
        run: |
          Copy-Item -Path .\dotnet\sdk\6.0.100-preview.7.21379.14 -Destination .\dotnet\sdk\6.0.100-${{env.BRANCH_VERSION}} -Recurse
          Copy-Item -Path .\artifacts\${{env.BRANCH_VERSION}}\NuGet.Build.Tasks\bin\Release\netstandard2.0\* -Destination .\dotnet\sdk\6.0.100-${{env.BRANCH_VERSION}}\
          $content = Get-Content -Path '.\dotnet\sdk\6.0.100-${{env.BRANCH_VERSION}}\.version'
          $newcontent = $content -replace '6.0.100-preview.7.21379.14', '6.0.100-${{env.BRANCH_VERSION}}'
          Set-Content -Path '.\dotnet\sdk\6.0.100-${{env.BRANCH_VERSION}}\.version' -Value $newcontent

      - name: Checkout test solutions
        run: |
          git clone --recursive https://github.com/dotnet/orleans
          Remove-Item -Path '.\orleans\global.json'
#          git clone --recursive https://github.com/OrchardCMS/OrchardCore.git
#          git clone --recursive https://github.com/NuGet/NuGet.Client.git

      - name: Disable strong name verification
        run: |
          reg DELETE "HKLM\Software\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f
          reg DELETE "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f
          
      - name: Benchmark v6.0.100-${{env.BASE_VERSION}}
        run: |
          Set-Content -Path 'global.json' -Value '{"sdk": { "version": "6.0.100-${{env.BASE_VERSION}}" } }'
          .\scripts\perftests\RunPerformanceTests.ps1 -nugetClientFilePath .\dotnet\dotnet.exe -solutionFilePath .\orleans\Orleans.sln -resultsFilePath results.csv -skipForceRestores -skipNoOpRestores -skipColdRestores -iterationCount ${{env.ITERATION_COUNT}} -staticGraphRestore
          
      - name: Benchmark v6.0.100-${{env.BRANCH_VERSION}}
        run: |
          Set-Content -Path 'global.json' -Value '{"sdk": { "version": "6.0.100-${{env.BRANCH_VERSION}}" } }'
          .\scripts\perftests\RunPerformanceTests.ps1 -nugetClientFilePath .\dotnet\dotnet.exe -solutionFilePath .\orleans\Orleans.sln -resultsFilePath results.csv -skipForceRestores -skipNoOpRestores -skipColdRestores -iterationCount ${{env.ITERATION_COUNT}} -staticGraphRestore
     
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: results_windows_dotnet
          path: results.csv
