name: benchmark_dotnet_windows

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  ITERATION_COUNT: 15
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  benchmark_dotnet_windows:
    runs-on: windows-2019
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download .NET Core SDK
        run: |
          curl -sSL https://download.visualstudio.microsoft.com/download/pr/c974c8da-7693-41c9-a874-712918a8964e/1d9223b00447537fef5f863cfa88cf80/dotnet-sdk-6.0.100-preview.7.21379.14-win-x64.zip -o dotnet.zip
          Expand-Archive dotnet.zip -DestinationPath dotnet
          Get-ChildItem
#      - name: Checkout test solutions
#        run: |
#          git clone --recursive https://github.com/dotnet/orleans
#          git clone --recursive https://github.com/OrchardCMS/OrchardCore.git
#          git clone --recursive https://github.com/NuGet/NuGet.Client.git

      - name: Disable strong name verification
        run: |
          reg DELETE "HKLM\Software\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f
          reg DELETE "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results.csv
