name: benchmark_dotnet_windows

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  ITERATION_COUNT: 15
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  benchmark_dotnet_windows:
    runs-on: windows-2019
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download .NET Core SDK
        run: |
          curl -sSL https://download.visualstudio.microsoft.com/download/pr/c974c8da-7693-41c9-a874-712918a8964e/1d9223b00447537fef5f863cfa88cf80/dotnet-sdk-6.0.100-preview.7.21379.14-win-x64.zip -o dotnet.zip
          Expand-Archive dotnet.zip -DestinationPath dotnet
          
          Copy-Item -Path .\dotnet\sdk\6.0.100-preview.7.21379.14\* -Destination .\dotnet\sdk\6.0.100-dev.838751441 -Recurse
          Copy-Item -Path .\artifacts\dev-838751441\NuGet.Build.Tasks\bin\Release\netstandard2.0\* -Destination .\dotnet\sdk\6.0.100-dev.838751441
          $content = Get-Content -Path .\dotnet\sdk\6.0.100-dev.838751441\.version
          $content = $content -replace '6.0.100-preview.7.21379.14', '6.0.100-dev.838751441'
          Set-Content -Path '.\dotnet\sdk\6.0.100-dev.838751441\.version' -Value $content
          
          Copy-Item -Path .\dotnet\sdk\6.0.100-preview.7.21379.14 -Destination .\dotnet\sdk\6.0.100-nommap.5a8b1c47a
          Copy-Item -Path .\artifacts\nommap.5a8b1c47a\NuGet.Build.Tasks\bin\Release\netstandard2.0\* -Destination .\dotnet\sdk\6.0.100-nommap.5a8b1c47a\
          $content = Get-Content -Path '.\dotnet\sdk\6.0.100-nommap.5a8b1c47a\.version'
          $content = $content -replace '6.0.100-preview.7.21379.14', '6.0.100-nommap.5a8b1c47a'
          Set-Content -Path '.\dotnet\sdk\6.0.100-nommap.5a8b1c47a\.version' -Value $content

#      - name: Checkout test solutions
#        run: |
#          git clone --recursive https://github.com/dotnet/orleans
#          git clone --recursive https://github.com/OrchardCMS/OrchardCore.git
#          git clone --recursive https://github.com/NuGet/NuGet.Client.git

      - name: Disable strong name verification
        run: |
          reg DELETE "HKLM\Software\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f
          reg DELETE "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results.csv
