name: benchmark_nuget_windows

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  ITERATION_COUNT: 1
  BASE_VERSION: dev.838751441
  BRANCH_VERSION: nommap.5a8b1c47a
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  benchmark_nuget_windows:
    runs-on: windows-2019
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout test solutions
        run: |
          git clone --recursive https://github.com/dotnet/orleans
          git clone --recursive https://github.com/OrchardCMS/OrchardCore.git
          git clone --recursive https://github.com/NuGet/NuGet.Client.git

      - name: Disable strong name verification
        run: |
          reg DELETE "HKLM\Software\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Microsoft\StrongName\Verification\*,*" /f
          reg DELETE "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification" /f
          reg ADD "HKLM\Software\Wow6432Node\Microsoft\StrongName\Verification\*,*" /f

      - name: Benchmark
        shell: pwsh
        run: |
          $solutions = @("NuGet.Client", "OrchardCore", "orleans")
          $versions = @("${{env.BASE_VERSION}}", "${{env.BRANCH_VERSION}}")
          For ($i=0; $i -lt 2; $i++) {
              ForEach ($solution In $solutions) {
                  ForEach ($version In $versions) {
                    .\scripts\perftests\RunPerformanceTests.ps1 -nugetClientFilePath .\artifacts\$version\NuGet.CommandLine\bin\Release\net472\NuGet.exe  -solutionFilePath $solution -resultsFilePath results.csv -skipForceRestores -skipNoOpRestores -skipColdRestores -iterationCount ${{env.ITERATION_COUNT}} -staticGraphRestore
                  }
              }
          }

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: results_windows_nuget
          path: results.csv
